In [1]:
import warnings
# 경고메시지 숨기기
# warnings.filterwarnings(action='ignore')

# Numpy 개요
http://www.numpy.org

In [2]:
import numpy as np
np.__version__

'1.24.3'

# 넘파이 배열 이해하기

## ndim(dimension, rank)
- 몇 차원인지 반환

In [4]:
a = np.array(0) # scalar
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [5]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [6]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [7]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [8]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [9]:
a.shape # depth, row, col

(2, 2, 3)

## shape

In [13]:
a = np.array(3)
a, a.shape

(array(3), ())

In [14]:
a = np.array([3])
a, a.shape

(array([3]), (1,))

In [15]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [16]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [17]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], 
              [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## size

In [18]:
a = np.array([1, 3, 5, 7, 9])
a.size

5

In [19]:
a = np.array([[1,2,3], [4, 5, 6]])
a.size

6

## 넘파이 배열

In [20]:
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [21]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5


In [22]:
myArr

array([10, 56, 77, 23, 44])

In [23]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [24]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape} 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3) 구조타입 = <class 'tuple'>, size = 9


In [25]:
# 2차원 리스트에서 각 행의 수가 다를 경우? 리스트는 상관이 없음
myList21 = [ [1,2,3,4],[10, 20 ,30, 40, 50],[100, 200, ]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [26]:
# 길이가 달라 에러 리턴 -> 행렬이 아니니까 에러
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
- 배열 간의 연산 가능. "브로드캐스팅", 요소별 연산 (element-wise)
- 넘파이 메서드 사용 가능: 평균, 상관계수, 분산, 표준편차 등
- 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [ ]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

In [ ]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

In [30]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [31]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
